;
;
;  Data for the vertical distribution of emissions
;
;

begin

Vert_Dist = True
Vert_Dist@Number_of_Layers = 6 
Vert_Dist@TRA = (/0.7, 0.3, 0.0, 0.0, 0.0, 0.0 /)
Vert_Dist@AGR = (/0.7, 0.3, 0.0, 0.0, 0.0, 0.0 /)
Vert_Dist@SHP = (/0.7, 0.3, 0.0, 0.0, 0.0, 0.0 /)
Vert_Dist@RES = (/0.7, 0.3, 0.0, 0.0, 0.0, 0.0 /)
Vert_Dist@IND = (/0.3, 0.4, 0.2, 0.1, 0.0, 0.0 /)
Vert_Dist@POW = (/0.0, 0.1, 0.2, 0.4, 0.2, 0.1 /)
Vert_Dist@SLV = (/0.7, 0.3, 0.0, 0.0, 0.0, 0.0 /)




end
